# Generated by Django 5.2.4 on 2025-08-06 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("habbits", "0002_alter_habbit_duration_seconds_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="habbit",
            options={
                "ordering": ["id"],
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
            },
        ),
    ]
